name: test-node-apis
run-name: Testing APIs
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
